wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720420738
    t:
      1:
      - 1
      - 5
      - 9
      - 37
      - 38
      - 41
      - 49
      - 53
      - 55
      - 63
      - 82
      - 103
      2:
      - 1
      - 5
      - 9
      - 37
      - 38
      - 41
      - 49
      - 53
      - 55
      - 63
      - 82
      - 103
      3:
      - 7
      - 23
      - 66
      4: 3.8.19
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-AdamW
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: learning_rate
      5: 1
      6:
      - 1
    - 1: temperature
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
